// This file is generated by npm run build:icons
 
export type IconList =
	| "account"
	| "arrowDownChevron"
	| "chat"
	| "close"
	| "collapse"
	| "expand"
	| "facebook"
	| "instagram"
	| "like"
	| "linkedin"
	| "send"
	| "youtube";
